services:
  web:
    build: 
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ../../app:/app
    environment:
      - ENVIRONMENT=development
    restart: always 