version: '3.8'

services:
  web:
    build: 
      context: ../..
      dockerfile: docker/main/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: always 